import type { Metadata } from "next";
import "./globals.css";
import styles from "./styles.module.css"
import localFont from "next/font/local";
import { Header, Footer } from "@/components";

const Golos_Text = localFont({
  src: "../assets/fonts/Variable_Golos_Text.woff2",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Golos_Text.className}>
        <Header />
        <main className={styles.Main}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
